# Generated by Django 6.0.6 on 2026-07-09 15:07

from django.db import migrations, models


def backfill_tipo_pago(apps, schema_editor):
    """Las facturas ya emitidas con payment_method='card'/'paypal' vienen del
    checkout de la Tienda: se pagaron online al instante, así que se marcan
    como Contado y se saldan. El resto (emitidas manualmente desde Ventas,
    sin payment_method) se dejan como Crédito, que es como ya estaban
    (saldo=total / PENDIENTE) desde la migración 0010.
    """
    Invoice = apps.get_model('billing', 'Invoice')
    Invoice.objects.filter(payment_method__in=['card', 'paypal']).update(
        tipo_pago='contado', saldo=0, estado_cobro='PAGADA',
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_invoice_saldo_estado_cobro'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tipo_pago',
            field=models.CharField(choices=[('contado', 'Contado'), ('credito', 'Crédito')], default='credito', max_length=10, verbose_name='Tipo de pago'),
        ),
        migrations.RunPython(backfill_tipo_pago, noop_reverse),
    ]
