# Generated by Django 6.0.6 on 2026-07-13 01:26

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0004_purchase_estado_pago_purchase_saldo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedetail',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='suppliercreditnote',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='suppliercreditnote',
            name='reason',
            field=models.CharField(max_length=300, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Motivo'),
        ),
    ]
