# Generated by Django 6.0.6 on 2026-07-15 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0005_alter_purchasedetail_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-purchase_date', '-id'], 'permissions': [('export_purchase_pdf', 'Can export Purchase PDF'), ('export_purchase_excel', 'Can export Purchase Excel')], 'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
    ]
