# Generated by Django 6.0.6 on 2026-07-09 14:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0010_invoice_saldo_estado_cobro'),
    ]

    operations = [
        migrations.CreateModel(
            name='CobroFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de pago')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor abonado')),
                ('observacion', models.TextField(blank=True, verbose_name='Observación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobros', to='billing.invoice', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Cobro de Factura',
                'verbose_name_plural': 'Cobros de Facturas',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
