# Generated by Django 6.0.6 on 2026-07-08 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_add_photo_customer_supplier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_account', to=settings.AUTH_USER_MODEL, verbose_name='Cuenta de usuario'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('card', 'Tarjeta'), ('paypal', 'PayPal')], max_length=10, null=True, verbose_name='Método de pago'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='paypal_order_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
