# Generated by Django 6.0.6 on 2026-07-13 01:26

import django.core.validators
import shared.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_invoice_tipo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='reason',
            field=models.CharField(max_length=300, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=100, validators=[shared.validators.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=100, validators=[shared.validators.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[shared.validators.validate_phone_ec]),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_name',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[shared.validators.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[shared.validators.validate_phone_ec]),
        ),
    ]
