# Generated by Django 6.0.6 on 2026-07-15 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_alter_creditnote_amount_alter_creditnote_reason_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-invoice_date'], 'permissions': [('export_pdf', 'Can export PDF'), ('export_excel', 'Can export Excel')]},
        ),
    ]
