# Generated by Django 6.0.6 on 2026-07-15 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_alter_invoice_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name'], 'permissions': [('export_brand_pdf', 'Can export Brand PDF'), ('export_brand_excel', 'Can export Brand Excel')], 'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['last_name', 'first_name'], 'permissions': [('export_customer_pdf', 'Can export Customer PDF'), ('export_customer_excel', 'Can export Customer Excel')]},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'permissions': [('export_product_pdf', 'Can export Product PDF'), ('export_product_excel', 'Can export Product Excel')], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productgroup',
            options={'ordering': ['name'], 'permissions': [('export_productgroup_pdf', 'Can export Product Group PDF'), ('export_productgroup_excel', 'Can export Product Group Excel')], 'verbose_name': 'Product Group', 'verbose_name_plural': 'Product Groups'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name'], 'permissions': [('export_supplier_pdf', 'Can export Supplier PDF'), ('export_supplier_excel', 'Can export Supplier Excel')], 'verbose_name': 'Supplier', 'verbose_name_plural': 'Suppliers'},
        ),
    ]
