# Generated by Django 6.0.6 on 2026-07-09 15:44

from django.db import migrations, models


def backfill_saldo(apps, schema_editor):
    """Las compras ya confirmadas no tenían seguimiento de pago: se dejan
    como Crédito (valor por defecto del campo) con saldo = total, igual
    que quedaban implícitamente antes de existir este módulo.
    """
    Purchase = apps.get_model('purchasing', 'Purchase')
    CONFIRMADA = 1
    for purchase in Purchase.objects.filter(estado=CONFIRMADA):
        purchase.saldo = purchase.total
        purchase.estado_pago = 'PAGADA' if purchase.total <= 0 else 'PENDIENTE'
        purchase.save(update_fields=['saldo', 'estado_pago'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0003_backfill_purchase_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='estado_pago',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada')], default='PENDIENTE', max_length=10, verbose_name='Estado de pago'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo pendiente de pago'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='tipo_pago',
            field=models.CharField(choices=[('contado', 'Contado'), ('credito', 'Crédito')], default='credito', max_length=10, verbose_name='Tipo de pago'),
        ),
        migrations.RunPython(backfill_saldo, noop_reverse),
    ]
